script_name('EFK')
script_version('1.0')
script_author('TMoore')

require "lib.moonloader"
local dlstatus = require('moonloader').download_status
local anotf, notify = pcall(import, 'lib_imgui_notf.lua')
local encoding = require "encoding"
local inicfg = require "inicfg"
local sampev = require "lib.samp.events"
local imgui = require "imgui"
local inicfg = require 'inicfg'
local fa = require 'fAwesome5'
local fa_glyph_ranges = imgui.ImGlyphRanges({ fa.min_range, fa.max_range })
imgui.ToggleButton = require('imgui_addons').ToggleButton
encoding.default = 'CP1251'
u8 = encoding.UTF8

-- Переменные
local WindowOne = imgui.ImBool(false)
local EFK = imgui.ImBool(false)
local Version_change = imgui.ImBuffer(65536)
local UpdatingWindow = imgui.ImBool(false)
local X, Y = getScreenResolution()
local Konst = imgui.ImBool(false)

local Version_Script = [[
Version 1.0
- Добавил ЕФК и Конституцию для сервера Меса.
- Добавил Авто-обновление.
]]

-- Version
VerEFK = 0.9
VerKonst = 0.9

function infinity()
    Version_change.v = u8:encode(Version_Script)
end

function imgui.CenterText(text)
    local width = imgui.GetWindowWidth()
    local calc = imgui.CalcTextSize(text)
    imgui.SetCursorPosX( width / 2 - calc.x / 2 )
    imgui.Text(text)
end

function imgui.TextColoredRGB(text)
    local style = imgui.GetStyle()
    local colors = style.Colors
    local ImVec4 = imgui.ImVec4

    local explode_argb = function(argb)
        local a = bit.band(bit.rshift(argb, 24), 0xFF)
        local r = bit.band(bit.rshift(argb, 16), 0xFF)
        local g = bit.band(bit.rshift(argb, 8), 0xFF)
        local b = bit.band(argb, 0xFF)
        return a, r, g, b
    end

    local getcolor = function(color)
        if color:sub(1, 6):upper() == 'SSSSSS' then
            local r, g, b = colors[1].x, colors[1].y, colors[1].z
            local a = tonumber(color:sub(7, 8), 16) or colors[1].w * 255
            return ImVec4(r, g, b, a / 255)
        end
        local color = type(color) == 'string' and tonumber(color, 16) or color
        if type(color) ~= 'number' then return end
        local r, g, b, a = explode_argb(color)
        return imgui.ImColor(r, g, b, a):GetVec4()
    end

    local render_text = function(text_)
        for w in text_:gmatch('[^\r\n]+') do
            local textsize = w:gsub('{.-}', '')
            local text, colors_, m = {}, {}, 1
            w = w:gsub('{(......)}', '{%1FF}')
            while w:find('{........}') do
                local n, k = w:find('{........}')
                local color = getcolor(w:sub(n + 1, k - 1))
                if color then
                    text[#text], text[#text + 1] = w:sub(m, n - 1), w:sub(k + 1, #w)
                    colors_[#colors_ + 1] = color
                    m = n
                end
                w = w:sub(1, n - 1) .. w:sub(k + 1, #w)
            end
            if text[0] then
                for i = 0, #text do
                    imgui.TextColored(colors_[i] or colors[1], u8(text[i]))
                    imgui.SameLine(nil, 0)
                end
                imgui.NewLine()
            else
                imgui.Text(u8(w))
            end
        end
    end
    render_text(text)
end

function imgui.OnDrawFrame()

    if not WindowOne.v and not Konst.v and not EFK.v and not UpdatingWindow.v then
        imgui.Process = false
    end

    if WindowOne.v then
        imgui.SetNextWindowSize(imgui.ImVec2(750, 460), imgui.Cond.FirstUseEver)
        imgui.SetNextWindowPos(imgui.ImVec2(X / 2, Y / 2), imgui.Cond.FirstUseEver, imgui.ImVec2(0.5, 0.5))
            imgui.Begin(u8'Единый Федеральный кодекс + Конституция Штата Меса | Версия: '..thisScript().version, WindowOne, imgui.WindowFlags.NoResize)
            imgui.SetCursorPos(imgui.ImVec2(175, 117.5))
            if imgui.Button(u8'ЕФК', imgui.ImVec2(200, 25)) then
                WindowOne.v = false
                    EFK.v = true
            end
            imgui.SameLine()
            if imgui.Button(u8'Конституция', imgui.ImVec2(200, 25)) then
                WindowOne.v = false
                    Konst.v = true
            end
            imgui.SetCursorPos(imgui.ImVec2(275, 150))
            if imgui.Button(u8'Проверить на обновления', imgui.ImVec2(200, 25)) then
                UpdatingWindow.v = true
                    WindowOne.v = false
            end
            imgui.NewLine()
            imgui.InputTextMultiline('##VersionBlog', Version_change, imgui.ImVec2(735, 255), imgui.InputTextFlags.ReadOnly)
            imgui.End()
    end

    if EFK.v then
        imgui.SetNextWindowSize(imgui.ImVec2(760, 460), imgui.Cond.FirstUseEver)
        imgui.SetNextWindowPos(imgui.ImVec2(X / 2, Y / 2), imgui.Cond.FirstUseEver, imgui.ImVec2(0.5, 0.5))
            imgui.Begin(u8'ЕФК | Версия: '..VerEFK, EFK, imgui.WindowFlags.NoResize)
                imgui.CenterText(u8'Единый Федеральный кодекс - нормативно-правовой акт, объединяющий в себе 3 законодательных акта:')
                imgui.CenterText(u8'Уголовный Кодекс')
                imgui.CenterText(u8'Административный Кодекс')
                imgui.CenterText(u8'Правила Дорожного Движения')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 1. Нападение')
                imgui.NewLine()
                imgui.TextColoredRGB('1.1 За нападение на гражданское лицо, преступнику присваивается 3-ий уровень розыска.')
                imgui.TextColoredRGB('1.2 За нападение на сотрудника правоохранительных органов, преступнику присваивается 6 уровень розыска, а также\nизымается лицензия на оружие.')
                imgui.TextColoredRGB('1.3 Убийство, причинение или угроза причинения вреда здоровью в отношении служащего армии преступнику\nприсваивается 4 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 2. Вооруженное нападение.')
                imgui.NewLine()
                imgui.TextColoredRGB('2.1 За вооруженное нападение преступнику присваивается 6-ой уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 3. Убийство.')
                imgui.NewLine()
                imgui.TextColoredRGB('3.1 За убийство преступнику присваивается 6 уровень розыска, а также изымается лицензия на оружие.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 4. Угон транспортного средства.')
                imgui.NewLine()
                imgui.TextColoredRGB('4.1 За попытку угона государственного или частного транспортного средства, преступнику присваивается 2 уровень\nрозыска.')
                imgui.TextColoredRGB('4.2 За угон транспортного средства, преступнику присваивается 4 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 5. Взятка и давление.')
                imgui.NewLine()
                imgui.TextColoredRGB('5.1 За дачу или попытку дачи взятки должностному лицу, гражданину присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('5.2 За получение взятки должностным лицом, ему присваивается 5 уровень розыска, {B8312F}увольнение из организации{FFFFFF},\n{000000}занесение в Черный Список{FFFFFF}, а так же наложение штрафа, втрое превышающего размер взятки.')
                imgui.TextColoredRGB('[{FF0000}!{FFFFFF} Чтобы офицер понёс наказание за коррупцию, вы должны предоставить руководству РП-доказательства, к примеру:\nЗапись диктофона или видео с видеорегистратора, с полагающейся РП-отыгровкой. {FF0000}!{FFFFFF}]')
                imgui.TextColoredRGB('{FF0000}Полиции запрещается полностью манипулировать ситуацией, не оставляя жертвам ни единого шанса,\nза бредовые махинации вроде "/me изъял все предметы для видеосъёмки, диктофон, часы и т.п.", будет следовать\nнаказание за PowerGaming.')
                imgui.TextColoredRGB('5.3 За давление на сотрудника правоохранительных органов, преступнику присваивается 2 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 6. Оружие.')
                imgui.NewLine()
                imgui.TextColoredRGB('6.1 За ношение оружия в открытом виде, преступнику присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('6.2 За ношение оружия без лицензии, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('6.3 За нелегальную покупку/продажу оружия, преступнику присваивается 6 уровня розыска.')
                imgui.TextColoredRGB('6.4 В случае обнаружения у задержанного патронов, и в случае если у гражданина нету лицензии на оружие,\nприсваивается 3 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 7. Взятие в заложники.')
                imgui.NewLine()
                imgui.TextColoredRGB('6.1 За ношение оружия в открытом виде, преступнику присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('6.2 За ношение оружия без лицензии, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('6.3 За нелегальную покупку/продажу оружия, преступнику присваивается 6 уровня розыска.')
                imgui.TextColoredRGB('6.4 В случае обнаружения у задержанного патронов, и в случае если у гражданина нету лицензии на оружие,\nприсваивается 3 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 7. Взятие в заложники.')
                imgui.NewLine()
                imgui.TextColoredRGB('7.1. За взятие одного или группы заложников, преступнику присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 8. Неподчинение.')
                imgui.NewLine()
                imgui.TextColoredRGB('8.1. За неподчинение сотруднику правоохранительных органов, находящемуся при исполнении,\nпреступнику присваивается 4 уровень розыска.')
                imgui.TextColoredRGB('8.2. За неподчинению сотруднику правоохранительных органов при обстановке ЧС в штате,\nа так же при проведении спец.операции, преступнику присваивается 6-ой уровень розыска.')
                imgui.TextColoredRGB('8.3 За отказ оплатить штраф, гражданину присваивается 2 уровень розыска, после чего он задерживается.')
                imgui.TextColoredRGB('8.4 За попытку удаления/удаление/порчу любого рода маячков, жучков, браслетов, определяющих местоположение,\nкоторыми сотрудники ФБР ограничили человека, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('8.5 За попытку скрыться от задержания , преступнику присваивается 3-й уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 9. Проникновение.')
                imgui.NewLine()
                imgui.TextColoredRGB('9.1. За проникновение на охраняемую правоохранительными органами территорию,\nгражданину присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('9.2. За проникновение на частную территорию без разрешения владельца, преступнику присваивается 2 уровень\nрозыска.')
                imgui.TextColoredRGB('9.3 За проникновение на территорию закрытой военной базы, преступнику присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 10. Наркотические вещества.')
                imgui.NewLine()
                imgui.TextColoredRGB('10.1 За хранение и/или перевозку наркотических средств, преступнику присваивается 5 уровень розыска,\nа так же изъятие наркотических средств.')
                imgui.TextColoredRGB('10.2 За сбыт и попытку приобрести наркотические средства, преступнику присваивается 6 уровень розыска\nи изъятие наркотических средств.')
                imgui.TextColoredRGB('10.3 За употребление наркотических средств, преступнику присваивается 6 уровень розыска\nи изъятие наркотических средств.')
                imgui.TextColoredRGB('10.4 За употребление и хранение наркотических веществ сотрудником правоохранительных органов карается\nувольнение с занесением в Черный список штата и присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('10.5 Посев или выращивание запрещенных к возделыванию растений, а также культивирование сортов\nконопли, мака или других растений, содержащих наркотические вещества присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 11. Терроризм.')
                imgui.NewLine()
                imgui.TextColoredRGB('11.1 За планирование/исполнение теракта, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('11.2 За подозрение в теракте или его попытке, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('11.3 За пребывание в террористической группировке, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('11.4 За вербовку в террористическую группировку, вербующему присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('11.5 За помощь/финансирование/исполнение теракта нарушителю присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 12. Дача ложных показаний.')
                imgui.NewLine()
                imgui.TextColoredRGB('12.1 За дачу ложных показаний сотрудникам правоохранительных органов, нарушителю присваивается\n3 уровень розыска.')
                imgui.TextColoredRGB('12.2 За неадекватный вызов сотрудников полиции, например:')
                imgui.TextColoredRGB('<< Копы вы овощи, быстро ко мне;')
                imgui.TextColoredRGB('Мусора;')
                imgui.TextColoredRGB('Алло, дебилы, сюда быстро')
                imgui.TextColoredRGB('и т.д >>')
                imgui.TextColoredRGB('Нарушителю присваивается 2 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 13. Хулиганство')
                imgui.NewLine()
                imgui.TextColoredRGB('{E25041}[К хулиганству приравнивается любое нарушение общественного порядка: стояние на крыше автомобиля,\n{E25041}нахождение на крыше остановки, ложный вызов на экстренную линию, флуд в любой чат одним и тем же сообщением.')
                imgui.TextColoredRGB('{E25041}Если человек толкает пустую машину с проезжей части на обочину, это не считается хулиганством.]')
                imgui.NewLine()
                imgui.TextColoredRGB('13.1 За хулиганство и неадекватное поведение в общественных местах, порчу имущества гражданских лиц,')
                imgui.TextColoredRGB('13.1 За хулиганство и неадекватное поведение в общественных местах, порчу имущества гражданских лиц,\nгосударственных организаций, преступнику присваивается 2 уровень розыска и наложение штрафа в размере $20.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 14. Митинг.')
                imgui.NewLine()
                imgui.TextColoredRGB('14.1 За вооруженное насилие, а так же призывы к насилию на митингах, преступнику присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('14.2 За участие в несанкционированном митинге преступнику присваивается 3-ий уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 15. Соучастие.')
                imgui.NewLine()
                imgui.TextColoredRGB('15.1 За соучастие в правонарушении, преступнику присваивается розыск за статью, по которой он нарушил.\nНо розыск снижается на 1 звезду.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 16. Вымогательство.')
                imgui.NewLine()
                imgui.TextColoredRGB('16.1 За вымогательство денежных средств, частной собственности, преступнику присваивается 4 уровень розыска.')
                imgui.TextColoredRGB('16.2 За вымогательство денежных средств, частной собственности должностным лицом, такому лицу\nприсваивается 6 уровень розыска, увольнение из гос.организации и занесение в Черный список организации.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 17. Помеха.')
                imgui.NewLine()
                imgui.TextColoredRGB('17.1 За помеху сотруднику правоохранительных органов, находящемуся при исполнении,\nпреступнику присваивается 3-ий уровень розыска.')
                imgui.TextColoredRGB('17.2 Пособничество в развале спецопераций, создание помех правоохранительным органам\nпри антитеррористической деятельности преступнику присваивается 4 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 18. Явка с повинной.')
                imgui.NewLine()
                imgui.TextColoredRGB('18.1 За явку с повинной с 2-4 уровнем розыска, преступнику снимается один уровень розыска.')
                imgui.TextColoredRGB('18.2 За явку с повинной с 5-6 уровнем розыска, преступнику снимается два уровня розыска.')
                imgui.TextColoredRGB('*Примечание: По данной статье имеют право работать только сотрудники от звания Детектив.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 19. Кража.')
                imgui.NewLine()
                imgui.TextColoredRGB('19.1 За кражу частного имущества, преступнику присваивается 4 уровень розыска.')
                imgui.TextColoredRGB('19.2 За кражу государственной собственности, собственности гос.организаций, имущества,\nматериалов, преступнику присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 20. Отказ от предоставления документов.')
                imgui.NewLine()
                imgui.TextColoredRGB('20.1 За отказ, нежелание гражданина от предоставления документов, удостоверяющих личность сотруднику\nправоохранительных органов, преступнику присваивается 2 уровень розыска.')
                imgui.TextColoredRGB('20.2 За отказ, нежелание гражданина от предоставления документов, удостоверяющих личность сотруднику\nправоохранительных органов в ситуации ЧС или спец.операции, преступнику присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 21. Наезд транспортным средством.')
                imgui.NewLine()
                imgui.TextColoredRGB('21.1 За наезд транспортным средством на гражданское лицо, преступнику присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('21.2 За наезд транспортным средством на сотрудника правоохранительных органов, преступнику\nприсваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 22. Оскорбление сотрудников правоохранительных органов.')
                imgui.NewLine()
                imgui.TextColoredRGB('22.1 За любой вид оскорбления сотрудника правоохранительных органов при исполнении,\nнарушителю присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('22.2 За неадекватное поведение в сторону сотрудника при исполнении, нарушителю\nприсваивается 3 уровень розыска.')
                imgui.TextColoredRGB('22.3 За провокации, нарушителю присваивается 3 уровень розыска.')
                imgui.TextColoredRGB('[ Выкрики подобно "– Давай! Стреляй, или ты боишься?!", оскорбительные жесты вроде\n"/me показал средний палец", "/me плюнул в лицо" и т.п. – примеры оснований для обвинений в провокации. ]')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 23. Сотрудничество лиц гос.организаций с ОПГ.')
                imgui.NewLine()
                imgui.TextColoredRGB('23.1 За сотрудничество лиц гос.организаций с нелегальной организованной группировкой,\nнарушителю присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 24. Воровство государственного имущества.')
                imgui.NewLine()
                imgui.TextColoredRGB('24.1 За кражу государственного имущества (патроны, одежда и т.д.) с военных объектов\nи зданий государственного значения, преступнику присваивается 6-ий уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 25. Превышение должностных полномочий')
                imgui.NewLine()
                imgui.TextColoredRGB('25.1 За превышение должностных полномочий с корыстной целью, должностному лицу присваивается\n6 уровень розыска с занесением в Черный Список [В тему на форуме].')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 26. Экстремизм')
                imgui.NewLine()
                imgui.TextColoredRGB('26.1 За призыв к экстремизму, нарушителю присваивается 6-ый уровень розыска.')
                imgui.TextColoredRGB('26.2 За проявления экстремизма, нарушителю присваивается 6-ый уровень розыска.')
                imgui.TextColoredRGB('26.3 За пребывание в экстремистской группировке преступнику присваивается 6 уровень розыска,\nа также вживляется маячок, по которому можно узнать местоположение человека.')
                imgui.TextColoredRGB('26.4 За вербовку в экстремистскую группировку, вербующему присваивается 6 уровень розыска.')
                imgui.TextColoredRGB('26.5 За помощь/финансирование экстремистской группировки нарушителю присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 27. Угрозы')
                imgui.NewLine()
                imgui.TextColoredRGB('27.1 За угрозы гражданину штата, нарушителю присваивается 3-ый уровень розыска.')
                imgui.TextColoredRGB('27.2 За угрозы сотруднику при исполнении, нарушителю присваивается 4-ый уровень розыска.')
                imgui.TextColoredRGB('27.3 За угрозы лидерам государственных организаций, нарушителю присваивается 6-ый уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 28. Нацизм')
                imgui.NewLine()
                imgui.TextColoredRGB('28.1 За призыв к нацизму, нарушителю присваивается 4-ый уровень розыска.')
                imgui.TextColoredRGB('28.2 За проявления нацизма, нарушителю присваивается 4-ый уровень розыска.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 29. Управление транспортным средством в нетрезвом виде')
                imgui.NewLine()
                imgui.TextColoredRGB('29.1 За управление транспортным средством в состоянии алкогольного или наркотического опьянения,\nнарушитель обязан выплатить штраф в размере $40.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 30. Использование мобильных телефонов за рулем.')
                imgui.NewLine()
                imgui.TextColoredRGB('30.1 За использование мобильных телефонов за рулем, во время вождения ТС, нарушитель обязан\nвыплатить штраф в размере $10.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 31. Езда по встречной полосе.')
                imgui.NewLine()
                imgui.TextColoredRGB('31.1 За управление транспортным средством по полосе встречного движения, нарушитель обязан\nвыплатить штраф в размере $10.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 32. Езда на Транспортном средстве.')
                imgui.NewLine()
                imgui.TextColoredRGB('32.1 За езду по железнодорожным путям - выписывается штраф $10.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 33. Нанесение вреда пешеходу.')
                imgui.NewLine()
                imgui.TextColoredRGB('33.1 За нанесение вреда пешеходу, в следствии ДТП, нарушитель обязан выплатить моральный ущерб\nпострадавшему (оценивается сотрудником Правоохранительных Органов).')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 34. Парковка и движение ТС в неположенном месте.')
                imgui.NewLine()
                imgui.TextColoredRGB('34.1 За парковку в неположенном месте, нарушитель обязан выплатить штраф в размере $5.000.')
                imgui.TextColoredRGB('34.2 За движение по тротуарам, велосипедным и пешеходным дорожкам нарушитель обязан выплатить штраф\nв размере $5.000.')
                imgui.TextColoredRGB('34.3 За движение по обочине нарушитель обязан выплатить штраф в размере $5.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 35. Затруднение движения.')
                imgui.NewLine()
                imgui.TextColoredRGB('35.1 За затруднение движения на проезжих частях, нарушитель обязан выплатить штраф в размере $10.000.')
                imgui.TextColoredRGB('35.2 За затруднение движения на проезжих частях, в следствии чего произошло ДТП,\nнарушитель обязан выплатить штраф в размере $20.000, а также моральный ущерб пострадавшему.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 36. ДТП.')
                imgui.NewLine()
                imgui.TextColoredRGB('36.1 При моральном и денежном приходе виновного и следующих лиц ДТП в примирению,\nДТП считается недействительным, и вызов сотрудника Правоохранительных Органов не обязателен.')
                imgui.TextColoredRGB('36.2 Виновник ДТП при наличии жертв объявляется в уголовный розыск (3 уровень розыска).')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 37. Пешеходы.')
                imgui.NewLine()
                imgui.TextColoredRGB('37.1 За переход дороги в неположенном месте, либо же за передвижение пешехода по проезжей части дороги,\nпешеходу нарушившему, полагается штраф в размере $5.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 38. Использование городского транспорта в личных целях.')
                imgui.NewLine()
                imgui.TextColoredRGB('38.1 За использование городского транспорта в личных целях, влечет за собой наказание в виде штрафа\nв размере $20.000.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 39. Незаконное ношение форменной одежды со знаком различия, с символикой государственных\nвоенизированных организаций, правоохранительных органах.')
                imgui.NewLine()
                imgui.TextColoredRGB('39.1 Незаконное ношение форменной одежды со знаками различия, с символикой государственных\nвоенизированных организаций, правоохранительных органов - влечет наложение 5-ого уровня розыска с конфискацией\nформенной одежды, знаков различия, символики государственных военизированных организаций, правоохранительных\nорганов.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 40. Езда с выключенными фарами.')
                imgui.NewLine()
                imgui.TextColoredRGB('40.1 За езду с выключенными фарами по шоссе, гражданину накладывается штраф в размере 15.000$.')
                imgui.TextColoredRGB('40.2 За езду с выключенными фарами по городской территории, гражданину накладывается штраф в размере 5.000$.')
                imgui.TextColoredRGB('40.3 За езду с выключенными фарами при плохой погоде которая влияет на видимость на дороге,\nгражданину накладывается штраф в размере 10.000$.')
                imgui.TextColoredRGB('40.4 За использование фар не по назначение, например слепить граждан в светлое время суток,\nгражданину накладывается штраф в размере 5.000$.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 41. Браконьерство.')
                imgui.NewLine()
                imgui.TextColoredRGB('41.1 За охоту в лесах штата без специальной лицензии, гражданину накладывается штраф в размере 30.000$.')
                imgui.NewLine()
                imgui.TextColoredRGB('Глава 42. Побег из-под стражи или ареста.')
                imgui.NewLine()
                imgui.TextColoredRGB('42.1 За побег из-под ареста или из-под стражи, нарушителю присваивается 6 уровень розыска.')
                imgui.NewLine()
                imgui.SetCursorPos(imgui.ImVec2(598, 5260))
                imgui.TextColoredRGB('Автор ЕФК: {8FDC7E}Toby Wilson')
                if imgui.Button(u8'Вернуться в меню', imgui.ImVec2(-1, 25)) then
                    EFK.v = false
                        WindowOne.v = true
                end
            imgui.End()
    end

    if Konst.v then
        imgui.SetNextWindowSize(imgui.ImVec2(780, 460), imgui.Cond.FirstUseEver)
        imgui.SetNextWindowPos(imgui.ImVec2(X / 2, Y / 2), imgui.Cond.FirstUseEver, imgui.ImVec2(0.5, 0.5))
            imgui.Begin(u8'Конституция | Версия: '..VerKonst, Konst, imgui.WindowFlags.NoResize)
                imgui.TextColoredRGB('{FBB426}К{FFFFFF}онституция Штата Меса')
                imgui.TextColoredRGB('{FBB426}А{FFFFFF}втор Конституции: Paul_Spataphore')
                imgui.TextColoredRGB('{FBB426}С{FFFFFF}одержание Основного Закона:')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Глава 1{FFFFFF}. Основы конституционного строя.')
                imgui.TextColoredRGB('{FBB426}Глава 2{FFFFFF}. Исполнительная власть.')
                imgui.TextColoredRGB('{FBB426}Глава 3{FFFFFF}. Законодательная власть.')
                imgui.TextColoredRGB('{FBB426}Глава 4{FFFFFF}. Судебная власть.')
                imgui.TextColoredRGB('{FBB426}Глава 5{FFFFFF}. Кабинет губернатора.')
                imgui.TextColoredRGB('{FBB426}Глава 6{FFFFFF}. Права и обязанности человека.')
                imgui.TextColoredRGB('{FBB426}Глава 7{FFFFFF}. Конституционные поправки и право сецессии.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 1{FFFFFF}. Основы конституционного строя.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 1')
                imgui.TextColoredRGB('Штат Меса является государственным образованием в составе Соединённых Штатов Америки, имеющим право на\nсецессию в установленном законом порядке.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 2')
                imgui.TextColoredRGB('Человек, его права и свободы являются высшей ценностью в штате Меса, их соблюдение и защита - обязанность\nгосударства. Умаление прав и законных интересов человека и гражданина не допускается.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 3')
                imgui.TextColoredRGB('Единственным источником власти в штате Меса является его народ. Высшим непосредственным выражением власти\nнарода в штате являются референдум и свободные выборы.\nНичто не может препятствовать свободному осуществлению народом своего избирательного права.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 4')
                imgui.TextColoredRGB('Конституция штата Меса имеет высшую юридическую силу, прямое действие и верховенство на всей территории штата,\nраспространяя на неё свой суверенитет.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 5')
                imgui.TextColoredRGB('Штат Меса состоит из восьми равноправных между собой округов - округ Лос-Сантос, округ Сан-Фиеро,\nокруг Лас-Вентурас, округ Рэд, округ Флинт, округ Боун, округ Уэтстоун, округ Тьерра-Робада.\nСтолицей и местом размещения правительства штата является город Лос-Сантос.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 6')
                imgui.TextColoredRGB('Каждый гражданин обладает на территории штата Меса всеми правами и свободами, а также несет равные обязанности,\nустановленные законом.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 7')
                imgui.TextColoredRGB('Государственная власть осуществляется на основе разделения на независимые друг от друга ветви - законодательную,\nисполнительную и судебную.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 8')
                imgui.TextColoredRGB('В штате Меса признаются идеологическое, политическое и конфессиональное многообразие.\nРегистрация политических партий остается за генеральной прокуратурой штата Меса.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 9')
                imgui.TextColoredRGB('Принимаемые законы и иные правовые акты не должны противоречить Конституции штата Меса.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 2{FFFFFF}. Исполнительная власть.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 10')
                imgui.TextColoredRGB('Губернатор является главой исполнительной власти и в соответствии с законами штата определяет основные\nнаправления внутренней политики.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 11')
                imgui.TextColoredRGB('1. Губернатор избирается сроком на один месяц открытым голосованием среди жителей штата, проживающих в штате\nне менее трёх лет.')
                imgui.TextColoredRGB('2. В случае, если ни один из кандидатов не смог набрать более половины голосов избирателей, проводится второй тур\nс участием двух кандидатов с наибольшим количеством голосов.')
                imgui.TextColoredRGB('3. На должность губернатора штата Меса не может претендовать лицо, имеющее судимость за совершение любых\nпреступлений, установленных уголовным законом. Все остальные критерии и цензы кандидатов на пост губернатора\nрегулируются соответствующим законодательством.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 12')
                imgui.TextColoredRGB('При вступлении в должность губернатор приносит на инаугурации следующую присягу:\n«Я торжественно клянусь, что буду добросовестно выполнять обязанности губернатора штата Меса\nи в полную меру моих сил буду поддерживать, охранять и защищать Конституцию штата Меса».')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 13')
                imgui.TextColoredRGB('Губернатор:')
                imgui.TextColoredRGB('1) является главой исполнительной власти;')
                imgui.TextColoredRGB('2) назначает и освобождает от должности председателя правительства;')
                imgui.TextColoredRGB('3) награждает почетными наградами и званиями;')
                imgui.TextColoredRGB('4) осуществляет помилование;')
                imgui.TextColoredRGB('5) имеет право вето в отношении законодательных актов Сената;')
                imgui.TextColoredRGB('6) распускает Сенат штата в случаях и порядке, установленными Конституцией штата;')
                imgui.TextColoredRGB('7) назначает выборы в Сенат штата в случаях и порядке, установленными Конституцией штата;')
                imgui.TextColoredRGB('8) назначает референдум в случаях и порядке, установленными Конституцией штата.')
                imgui.TextColoredRGB('9) назначает генерального прокурора штата Меса.')
                imgui.TextColoredRGB('10) утверждает структуру и состав подразделений, отделов и офисов государственных структур и департаментов.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 14')
                imgui.TextColoredRGB('Губернатор при исключительных обстоятельствах вводит на территории штата Меса или в отдельных его местностях\nчрезвычайное положение на срок не более двух недель. Необходимость продления чрезвычайного положения\nрассматривается на внеочередной сессии Сената и оно не может быть продлено более чем на месяц.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 15')
                imgui.TextColoredRGB('1. Губернатор издает указы и распоряжения, обязательные для исполнения на всей территории штата Меса.')
                imgui.TextColoredRGB('2. Указы и распоряжения губернатора не должны противоречить Конституции штата Меса и законам штата.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 16')
                imgui.TextColoredRGB('1. Губернатор прекращает исполнение полномочий досрочно в случае его отставки, неспособности по состоянию\nздоровья осуществлять принадлежащие ему полномочия или вынесения ему импичмента.')
                imgui.TextColoredRGB('2. Во всех случаях, когда губернатор не в состоянии выполнять свои обязанности, их временно исполняет председатель\nправительства штата вплоть до вступления в должность нового губернатора, избранного не позднее чем через две\nнедели.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 17')
                imgui.TextColoredRGB('1. Губернатор может быть отрешен Сенатом путем импичмента только на основании выдвинутого верховным судьей\nвотума недоверия в случае нарушения конституционного строя.')
                imgui.TextColoredRGB('2. Решение Сената о вынесении губернатору импичмента должно быть принято 3/4 голосов с последующим\nположительным заключением Конституционного суда.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 18')
                imgui.TextColoredRGB('Председатель правительства является заместителем губернатора и в соответствии с законами штата ведёт\nполный контроль над кабинетом губернатора.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 19')
                imgui.TextColoredRGB('1. Председатель правительства назначается губернатором на время срока правления губернатора.')
                imgui.TextColoredRGB('2. На должность председателя правительства штата Меса не может претендовать лицо, имеющее судимость\nза совершение любых преступлений, установленных уголовным законом.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 20')
                imgui.TextColoredRGB('Председатель правительства:')
                imgui.TextColoredRGB('1) является вторым лицом штата;')
                imgui.TextColoredRGB('2) вносит рекомендации и кандидатуры на посты советников губернатора;')
                imgui.TextColoredRGB('3) награждает почетными наградами и званиями;')
                imgui.TextColoredRGB('4) осуществляет помилование.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 21')
                imgui.TextColoredRGB('1. Председатель правительства издает указы и распоряжения, обязательные для исполнения на всей территории штата\nМеса.')
                imgui.TextColoredRGB('2. Указы и распоряжения председателя правительства не должны противоречить Конституции штата Меса и законам\nштата.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 22')
                imgui.TextColoredRGB('Председатель правительства может быть отстранен губернатором на основе утраты доверия, неэффективной работы\nили нарушением конституционного строя.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 3{FFFFFF}. Законодательная власть.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 23')
                imgui.TextColoredRGB('Сенат является законодательным органом штата Меса, главой которого является вице-губернатор, который ведет\nзаседания и ведает внутренним распорядком.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 24')
                imgui.TextColoredRGB('1. Сенат состоит из 10 сенаторов. Мандаты сенаторов распределяются между партиями пропорциональной системой.')
                imgui.TextColoredRGB('2. На выборы в Сенат могут быть зарегистрированны только официальные партии штата, которые имеют регистрацию\nгенеральной прокуратуры штата Меса.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 25')
                imgui.TextColoredRGB('1. Сенат избирается сроком на два месяца открытым голосованием среди жителей штата, проживающих в штате\nне менее 12-ти лет.')
                imgui.TextColoredRGB('2. Сенатор может быть лишен мандата путем открытого голосования большинством голосов с санкции Верховного\nсудьи в случае, если в отношении него имеются обоснованные подозрения в совершении им тяжкого преступления.')
                imgui.TextColoredRGB('3. Сенаторы имеют иммунитет от любого преследования и не могут быть задержаны, арестованы, подвергнуты\nобыску без санкции верховного судьи, кроме случаев задержания на месте преступления.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 26')
                imgui.TextColoredRGB('Заседания сената являются закрытыми и проводятся под защитой вооруженной охраны. Губернатор и председатель\nправительства могут присутствовать на заседаниях по приглашению вице-губернатора и выступать с речью,\nно не имеют права голоса. Верховный судья может по своему усмотрению присутствовать на заседаниях сената и\nвыступать с речью.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 27')
                imgui.TextColoredRGB('К ведению Сената относится:')
                imgui.TextColoredRGB('1) принятие законодательных актов и постановлений;')
                imgui.TextColoredRGB('2) вынесение импичмента губернатору;')
                imgui.TextColoredRGB('3) назначение на должность Верховного судьи [ПРЕДВАРИТЕЛЬНЫЙ ОБЗВОН];')
                imgui.TextColoredRGB('4) назначение на должность вице-губернатора [ПРЕДВАРИТЕЛЬНЫЙ ОБЗВОН];')
                imgui.TextColoredRGB('5) образование комитетов и комиссий;')
                imgui.TextColoredRGB('6) осуществление амнистии;')
                imgui.TextColoredRGB('7) финансовый и бюджетный контроль.')
                imgui.TextColoredRGB('8) осуществление контроля работы исполнительной ветви власти;')
                imgui.TextColoredRGB('9) проведение контроля правительства.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 28')
                imgui.TextColoredRGB('1. Вице-губернатор является спикером Сената и назначается Сенатом. До избрания вице-губернатора заседание должен\nвести самый старший по возрасту сенатор.')
                imgui.TextColoredRGB('2. В случае, если на должность вице-губернатора назначается Сенатор, то его мандат передается гос. структуре, от\nкоторой он был избран.')
                imgui.TextColoredRGB('3. Вице-губернатор имеет право голоса при рассмотрении законопроекта в случае, если голоса разделились поровну.')
                imgui.TextColoredRGB('4. Вице-губернатор прекращает исполнение полномочий досрочно в случае его отставки губернатором, неспособности\nпо состоянию здоровья осуществлять принадлежащие ему полномочия или выдвижением ему вотума\nнедоверия 3/4 голосов.')
                imgui.TextColoredRGB('5. Сенат штата может выразить недоверие вице-губернатору. Постановление о недоверии вице-губернатору\nпринимается большинством голосов от общего числа Сенаторов. После выражения Сенатом штата недоверия\nвице-губернатору, губернатор вправе объявить об отставке вице-губернатора, либо не согласиться с решением\nСената штата. В случае если Сенат штата в течение трех дней повторно выразит недоверие вице-губернатору,\nгубернатор объявляет об отставке вице-губернатора либо распускает Сенат штата, назначая новые выборы.')
                imgui.TextColoredRGB('6. Вице-губернатор может поставить перед Сенатом штата вопрос о доверии к нему. Если Сенат штата в доверии\nотказывает, губернатор в течение семи дней принимает решение об отставке вице-губернатора или о роспуске\nСената штата и назначении новых выборов.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 29')
                imgui.TextColoredRGB('1. Право законодательной инициативы принадлежит сенаторам, губернатору, председателю правительства,\nгенеральному прокурору, советникам, вице-губернатору и верховному судье.')
                imgui.TextColoredRGB('2. Законодательные акты и постановления принимаются большинством голосов от общего числа сенаторов.')
                imgui.TextColoredRGB('3. Принятые Сенатом законодательные акты по истечении семи дней должны быть подписаны губернатором,\nопубликованы - вице-губернатором. Принятые Сенатом постановления вступают в силу с момента их принятия\nи должны быть опубликованы вице-губернатором в этот же день.')
                imgui.TextColoredRGB('4. Губернатор имеет право «вето», то есть право отмены в одностороннем порядке принятого Сенатом\nзаконодательного акта до момента его подписания, то есть в течение семи дней. Право вето не распространяется на\nпостановления Сенатом - решение о назначении или отстранении от должности,\nрешение о вынесении импичмента, решение об учреждении комитета или комиссии и прочие исполнительные решения.')
                imgui.TextColoredRGB('5. После двукратного отклонения представленных кандидатур на должность вице-губернатора,\nгубернатор назначает самостоятельно вице-губернатора [ПРЕДВАРИТЕЛЬНО ОБЗВОН], распускает Сенат штата\nи назначает новые выборы.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 4{FFFFFF}. Судебная власть.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 30')
                imgui.TextColoredRGB('Судебная власть осуществляется посредством гражданского, административного, уголовного и конституционного\nсудопроизводства. Судебная система устанавливается исключительно Конституцией штата Меса.\nСоздание чрезвычайных судов не допускается.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 31')
                imgui.TextColoredRGB('1. Верховный судья избирается открытым голосованием из числа сенатаров на первой сессии нового созыва большинством.\nголосов. Также кандидатура Верховного судьи может быть выдвинута губернатором [ПРЕДВАРИТЕЛЬНО ОБЗВОН].')
                imgui.TextColoredRGB('2. Мандат сенатора избранного Верховным судьей передается партии, от которой он был избран.')
                imgui.TextColoredRGB('3. Верховный судья прекращает исполнение полномочий досрочно в случае его отставки, неспособности по состоянию\nздоровья осуществлять принадлежащие ему полномочия или переизбрания его двумя третями голосов.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 32')
                imgui.TextColoredRGB('1. Конституционный суд штата Меса является органом конституционного контроля и состоит из Верховного судьи\nа также двух независимых экспертов, назначаемых губернатором и вице-губернатором соответственно.')
                imgui.TextColoredRGB('2. Конституционный суд по запросам губернатора или Сената разрешает дела о соответствии Конституции штата Меса\nзаконодательных актов, указов губернатора, постановлений Сената или других распоряжений')
                imgui.TextColoredRGB('государственных организаций. Конституционный суд разрешает споры о компетенции между органами государственной\nвласти и по запросам губернатора или Сената дает толкование Конституции штата Меса.')
                imgui.TextColoredRGB('3. Законодательные акты, указы губернатора, постановления Сената, другие распоряжения государственных\nорганизаций или их отдельные положения, признанные Конституционным судом неконституционными, утрачивают\nзаконную силу и подлежат немедленной отмене.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 33')
                imgui.TextColoredRGB('1. Губернатор, председатель правительства, вице-губернатор и верховный судья обладают неприкосновенностью.')
                imgui.TextColoredRGB('2. Неприкосновенность означает, что обладающие ей лица не могут быть привлечены к уголовной или\nадминистративной ответственности, а также задержаны, арестованы, подвергнуты обыску или допросу.\nНеприкосновенность распространяется на занимаемые ими жилые и служебные помещения, используемые ими\nтранспортные средства, средства связи, принадлежащие им документы и багаж, на их переписку.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 5{FFFFFF}. Кабинет губернатора.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 34')
                imgui.TextColoredRGB('Кабинет губернатора является одним из главных исполнительных органов власти, состоящий из 4 советников:\nсоветник по вооруженным силам, советник по правоохранительным органам, советник по здравоохранению и\nсоветник по социальной и экономическим сферам.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 35')
                imgui.TextColoredRGB('1. Кабинет губернатора возглавляется председателем правительства .')
                imgui.TextColoredRGB('2. Советники назначаются губернатором по рекомендации председателя правительства или по рекомендации Сената\nштата Меса [ПРЕДВАРИТЕЛЬНО ОБЗВОН].')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 36')
                imgui.TextColoredRGB('1. Губернатор формирует Государственный совет, состоящий из четырёх государственных советников, подконтрольных\nисключительно губернатору и председателю правительства.')
                imgui.TextColoredRGB('2. Государственный совет является высшим совещательным органом при губернаторе.')
                imgui.TextColoredRGB('3. Государственный совет разрабатывает и представляет губернатору проекты формирования бюджета, управляет\nгосударственным имуществом по поручению губернатора или председателя правительства, выносит совещательные\nрешения в виде постановлений или заключений по вопросам компетенции исполнительной власти,\nоказывает иное содействие губернатору в реализации полномочий, предусмотренных его компетенцией;')
                imgui.TextColoredRGB('4. Члены Государственного совета могут быть отстранены от своих служебных полномочий указом губернатора штата Меса.')
                imgui.TextColoredRGB('5. Члены Государственного совета (государственные советники) имеют иммунитет от любого преследования и не могут\nбыть задержаны, арестованы, подвергнуты обыску без санкции верховного судьи, кроме случаев задержания\nна месте преступления.')
                imgui.TextColoredRGB('6. Все решения и постановления Государственного совета имеют исключительно рекомендательный характер.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 37')
                imgui.TextColoredRGB('1. Советник по социальной и экономическим сферам ведёт контроль над экономической и социальной составляющей\nгосударства и ведёт мониторинг государственного консолидированного бюджета.')
                imgui.TextColoredRGB('2. Советник по правоохранительным органам (министерству юстиции) ведёт контроль над правоохранительными органами.')
                imgui.TextColoredRGB('3. Советник по вооруженным силам (министерству обороны) ведёт контроль над вооруженными силами штата Меса.')
                imgui.TextColoredRGB('5. Советник по здравоохранению (министерству здравоохранения) ведёт контроль над всеми медицинскими центрами.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 38')
                imgui.TextColoredRGB('Советник по социальной и экономическим сферам:')
                imgui.TextColoredRGB('1) возглавляет экономическую и социальные сферы штата;')
                imgui.TextColoredRGB('2) ведёт мониторинг бюджета штата Меса, контролирует поток государственных денег;')
                imgui.TextColoredRGB('3) занимается антикоррупционной деятельностью;')
                imgui.TextColoredRGB('4) формирует социальные программы от лица правительства штата Меса;')
                imgui.TextColoredRGB('5) контролирует государственные закупки социальной сферы;')
                imgui.TextColoredRGB('6) подотчётен председателю правительства и губернатору.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 39')
                imgui.TextColoredRGB('Советник по вооруженным силам:')
                imgui.TextColoredRGB('1) возглавляет вооруженные силы штата;')
                imgui.TextColoredRGB('2) следит за полной боевой готовностью вооруженных сил штата;')
                imgui.TextColoredRGB('3) контролирует государственные закупки в сфере военно-промышленного комплекса;')
                imgui.TextColoredRGB('4) проводит плановые проверки вооруженных сил (рекомендательный характер);')
                imgui.TextColoredRGB('5) занимается организацией вооруженных сил штата Меса;')
                imgui.TextColoredRGB('6) подотчётен председателю правительства и губернатору.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 40')
                imgui.TextColoredRGB('Советник по правоохранительным органам:')
                imgui.TextColoredRGB('1) следит за работоспособностью правоохранительных органов;')
                imgui.TextColoredRGB('2) контролирует государственные закупки в сфере ПО;')
                imgui.TextColoredRGB('3) проводит плановые проверки правоохранительным органам (рекомендательный характер);')
                imgui.TextColoredRGB('4) формирует плановые работы для департаментов полиции;')
                imgui.TextColoredRGB('5) подотчётен председателю правительства и губернатору.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 41')
                imgui.TextColoredRGB('Советник по здравоохранению:')
                imgui.TextColoredRGB('1) возглавляет систему здравоохранению штата;')
                imgui.TextColoredRGB('2) следит за работоспособностью всех больниц штата;')
                imgui.TextColoredRGB('3) контролирует государственные закупки в сфере здравоохранения;')
                imgui.TextColoredRGB('4) проводит плановые проверки государственных центров здравоохранения (рекомендательный характер);')
                imgui.TextColoredRGB('5) подотчётен председателю правительства и губернатору.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 42')
                imgui.TextColoredRGB('1. Государственные закупки - заказ государственных органов от имени публично-правового образования, оплачиваемый\nиз соответствующих бюджетов.')
                imgui.TextColoredRGB('2. Государственные закупки инициируются кабинетом губернатора (государственным советом) и передаются на\nрассмотрение комитету по экономике при Сенате.')
                imgui.TextColoredRGB('3. Комитет по экономике обязуется рассмотреть запрос государственного контракта и, в случае прохождения заказа\nпо всем критериям государственной закупки, опубликовать в кратчайшие сроки на официальном сайте комитета\nпо экономике при Сенате штата Меса.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 6{FFFFFF}. Права и обязанности человека.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 43')
                imgui.TextColoredRGB('Обеспечение прав и свобод граждан штата Меса является высшей целью государства. Каждый имеет право на достойный\nуровень жизни, включая достаточное питание, одежду, жилье и постоянное улучшение необходимых для этого условий.\nГосударство гарантирует права и свободы граждан штата, закрепленные в Конституции, законах и предусмотренные\nмеждународными обязательствами государства.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}{FBB426}Статья 44')
                imgui.TextColoredRGB('Все равны перед законом и имеют право без всякой дискриминации на равную защиту прав и законных интересов.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 45')
                imgui.TextColoredRGB('Ограничение прав и свобод личности допускается только в случаях, предусмотренных законом, в интересах национальной\nбезопасности, общественного порядка, защиты нравственности, здоровья населения, прав и свобод других лиц. Никто не\nможет пользоваться преимуществами и привилегиями, противоречащими закону.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 46')
                imgui.TextColoredRGB('Каждый имеет право на жизнь. Государство защищает жизнь человека от любых противоправных посягательств. Смертная\nказнь до ее отмены может применяться в соответствии с законом как исключительная мера наказания за особо тяжкие\nпреступления и только согласно приговору суда.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 47')
                imgui.TextColoredRGB('Государство обеспечивает свободу, неприкосновенность и достоинство личности. Ограничение или лишение личной\nсвободы возможно в случаях и порядке, установленных законом. Лицо, заключенное под стражу, имеет право на судебную\nпроверку законности его задержания или ареста. Никто не должен подвергаться пыткам, жестокому, бесчеловечному либо\nунижающему его достоинство обращению или наказанию, а также без его согласия подвергаться медицинским или иным\nопытам.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 48')
                imgui.TextColoredRGB('Никто не может быть признан виновным в преступлении, если его вина не будет в предусмотренном законом порядке\nдоказана и установлена вступившим в законную силу приговором суда. Обвиняемый не обязан доказывать свою\nневиновность.')
                imgui.TextColoredRGB('Гражданин может быть признан виновным в преступлении, если он самолично решил не использовать своё право\nна судебную защиту.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 49')
                imgui.TextColoredRGB('Никто не должен принуждаться к даче показаний и объяснений против самого себя, членов своей семьи, близких\nродственников. Доказательства, полученные с нарушением закона, не имеют юридической силы.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 50')
                imgui.TextColoredRGB('Каждый имеет право на защиту от незаконного вмешательства в его личную жизнь, в том числе от посягательства на тайну\nего корреспонденции, телефонных и иных сообщений, на его честь и достоинство.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 51')
                imgui.TextColoredRGB('Неприкосновенность жилища и иных законных владений граждан гарантируется. Никто не имеет права без законного\nоснования войти в жилище и иное законное владение гражданина против его воли.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 52')
                imgui.TextColoredRGB('Граждане штата имеют право свободно передвигаться и выбирать место жительства в пределах штата Меса, покидать ее и\nбеспрепятственно возвращаться обратно.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 53')
                imgui.TextColoredRGB('Каждый имеет право самостоятельно определять свое отношение к религии, единолично или совместно с другими\nисповедовать любую религию или не исповедовать никакой, выражать и распространять убеждения, связанные с\nотношением к религии, участвовать в отправлении религиозных культов, ритуалов, обрядов, не запрещенных законом.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 54')
                imgui.TextColoredRGB('Каждому гарантируется свобода мнений, убеждений и их свободное выражение. Никто не может быть принужден к\nвыражению своих убеждений или отказу от них. Монополизация средств массовой информации государством,\nобщественными объединениями или отдельными гражданами, а также цензура не допускаются.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 55')
                imgui.TextColoredRGB('Гражданам штата Меса гарантируется право на получение, хранение и распространение полной, достоверной\nи своевременной информации о деятельности государственных органов, общественных объединений, о политической,\nэкономической, культурной и международной жизни, состоянии окружающей среды. Государственные органы\nобщественные объединения, должностные лица обязаны предоставить гражданину штата Меса возможность ознакомиться\nс материалами, затрагивающими его права и законные интересы. Пользование информацией может быть ограничено\nзаконодательством в целях защиты чести, достоинства, личной и семейной жизни граждан и полного осуществлениями\nсвоих прав.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 56')
                imgui.TextColoredRGB('Свобода собраний, митингов, уличных шествий, демонстраций и пикетирования, не нарушающих правопорядок и права\nдругих граждан штата Меса, гарантируется государством. Порядок проведения указанных мероприятий определяется\nзаконом.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 57')
                imgui.TextColoredRGB('Каждый имеет право на свободу объединений. Каждый имеет право вступить в активную на данный момент партию.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 58')
                imgui.TextColoredRGB('Граждане штата Меса имеют право участвовать в решении государственных дел как непосредственно, так и через свободно\nизбранных представителей. Непосредственное участие граждан в управлении делами общества и государства\nобеспечивается проведением референдумов, обсуждением проектов законов и вопросов штатского значения, другими\nопределенными законом способами. В порядке, установленном законодательством, граждане штата Меса принимают\nчастие в обсуждении вопросов государственной и общественной жизни на штатских собраниях.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 59')
                imgui.TextColoredRGB('Граждане штата Меса имеют право свободно избирать и быть избранными в государственные органы на основе всеобщего,\nравного, прямого или косвенного избирательного права при тайном голосовании.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 60')
                imgui.TextColoredRGB('Граждане штата Меса в соответствии со своими способностями, профессиональной подготовкой имеют право равного\nдоступа к любым должностям в государственных органах.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 61')
                imgui.TextColoredRGB('Каждый имеет право направлять личные или коллективные обращения в государственные органы.\nГосударственные органы, а также должностные лица обязаны рассмотреть обращение и дать ответ по существу в\nопределенный законом срок. Отказ от рассмотрения поданного заявления должен быть письменно мотивированным.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 62')
                imgui.TextColoredRGB('Гражданам штата Меса гарантируется право на труд как наиболее достойный способ самоутверждения человека, то есть\nправо на выбор профессии, рода занятий и работы в соответствии с призванием, способностями, образованием,\nпрофессиональной подготовкой и с учетом общественных потребностей, а также на здоровые и безопасные условия труда.\nГосударство создает условия для полной занятости населения. В случае незанятости лица по не зависящим от него\nпричинам ему гарантируется обучение новым специальностям и повышение квалификации с учетом общественных\nпотребностей, а также пособие по безработице в соответствии с законом. Граждане имеют право на защиту своих\nэкономических и социальных интересов, включая право на объединение в профессиональные союзы, заключение\nколлективных договоров (соглашений) и право на забастовку. Принудительный труд запрещается, кроме работы или\nслужбы, определяемой приговором суда или в соответствии с законом о чрезвычайном и военном положении.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 63')
                imgui.TextColoredRGB('Каждый гражданин штата Меса имеет право на отдых и на оплачиваемый отпуск со стороны своего работодателя.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 64')
                imgui.TextColoredRGB('Государство гарантирует каждому право собственности и содействует ее приобретению. Собственник имеет право владеть,\nпользоваться и распоряжаться имуществом как единолично, так и совместно с другими лицами. Неприкосновенность\nсобственности, право ее наследования охраняются законом. Собственность, приобретенная законным способом,\nзащищается государством. Государство поощряет и охраняет сбережения граждан, создает гарантии возврата вкладов.\nПринудительное отчуждение имущества допускается лишь по мотивам общественной необходимости при\nоблюдении условий и порядка, определенных законом, со своевременным и полным компенсированием стоимости\nотчужденного имущества, а также согласно постановлению суда. Осуществление права собственности не должно\nпротиворечить общественной пользе и безопасности, наносить вреда окружающей среде, историко-культурным ценностям,\nущемлять права и защищаемые законом интересы других лиц.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 65')
                imgui.TextColoredRGB('Гражданам штата Меса гарантируется право на охрану здоровья. Государство создает условия доступного для всех граждан\nмедицинского обслуживания. Право граждан штата Меса на охрану здоровья обеспечивается также развитием физической\nкультуры и спорта, мерами по оздоровлению окружающей среды, возможностью пользования оздоровительными\nучреждениями, совершенствованием охраны труда.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 66')
                imgui.TextColoredRGB('Гражданам штата Меса гарантируется право на социальное обеспечение в старости, в случае болезни, инвалидности,\nутраты трудоспособности, потери кормильца и в других случаях, предусмотренных законом. Государство проявляет\nособую заботу о ветеранах войны и труда, а также о лицах, утративших здоровье при защите государственных и\nобщественных интересов.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 67')
                imgui.TextColoredRGB('Граждане штата Меса имеют право на жилище. Это право обеспечивается развитием государственного и частного\nжилищного фонда, содействием гражданам в приобретении жилья. Никто не может быть произвольно лишен жилья')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 68')
                imgui.TextColoredRGB('Каждый имеет право на образование. Гарантируются доступность и бесплатность общего среднего и\nпрофессионально-технического образования. Среднее специальное и высшее образование доступно для всех в\nсоответствии со способностями каждого. Каждый может на конкурсной основе бесплатно получить соответствующее\nобразование в государственных учебных заведениях.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 69')
                imgui.TextColoredRGB('Каждый имеет право сохранять свою национальную принадлежность, равно как никто не может быть принужден к\nопределению и указанию национальной принадлежности. Оскорбление национального достоинства преследуется согласно\nзакону. Каждый имеет право пользоваться родным языком, выбирать язык общения. Государство гарантирует в\nсоответствии с законом свободу выбора языка воспитания и обучения.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 70')
                imgui.TextColoredRGB('Каждый, кто находится на территории штата Меса, обязан соблюдать его Конституцию, законы и уважать национальные\nтрадиции.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 71')
                imgui.TextColoredRGB('Каждый обязан уважать достоинство, права, свободы, законные интересы других лиц.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 72')
                imgui.TextColoredRGB('Каждый обязан беречь историко-культурное, духовное наследие и другие национальные ценности.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 73')
                imgui.TextColoredRGB('Охрана природной среды – долг каждого.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 74')
                imgui.TextColoredRGB('Граждане штата Меса обязаны принимать участие в финансировании государственных расходов путем уплаты\nгосударственных налогов, пошлин и иных платежей.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 75')
                imgui.TextColoredRGB('Никто не может быть принужден к исполнению обязанностей, не предусмотренных Конституцией штата Меса и его\nзаконами, либо к отказу от своих прав.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 76')
                imgui.TextColoredRGB('Каждому гарантируется защита его прав и свобод компетентным, независимым и беспристрастным судом в определенные\nзаконом сроки. С целью защиты прав, свобод, чести и достоинства граждане в соответствии с законом вправе взыскать в\nсудебном порядке как имущественный вред, так и материальное возмещение морального вреда.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 77')
                imgui.TextColoredRGB('Каждый имеет право на юридическую помощь для осуществления и защиты прав и свобод, в том числе право пользоваться\nв любой момент помощью адвокатов и других своих представителей в суде, иных государственных органах, органах\nместного управления, на предприятиях, в учреждениях, организациях, общественных объединениях и в отношениях с\nдолжностными лицами и гражданами. В случаях, предусмотренных законом, юридическая помощь оказывается за счет\nгосударственных средств. Противодействие оказанию правовой помощи в штате Меса запрещается.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 78')
                imgui.TextColoredRGB('Осуществление предусмотренных настоящей Конституцией прав и свобод личности может быть приостановлено только в\nусловиях чрезвычайного или военного положения в порядке и пределах, определенных Конституцией и законом.')
                imgui.NewLine()
                imgui.TextColoredRGB('{F37934}Глава 7{FFFFFF}. Конституционные поправки и право сецессии.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 79')
                imgui.TextColoredRGB('1. Сецессия – конституционный процесс выхода штата Меса из состава Соединенных Штатов Америки на основании\nволеизъявления народа.')
                imgui.TextColoredRGB('2. Инициировать референдум о сецессии имеет право губернатор, обратившись с соответствующим обращением в\nКонституционный суд штата. После вынесения положительного заключения, в течение двух недель должен быть проведен\nвсеобщий референдум. В случае успешного голосования, итоги референдума должны быть ратифицированы расширенной\nколлегией Сената двумя третями голосов.')
                imgui.NewLine()
                imgui.TextColoredRGB('{FBB426}Статья 80')
                imgui.TextColoredRGB('Положения глав 1, 6 и 7 Конституции не могут быть пересмотрены, в ином случае принимается новая Конституция.')
                imgui.NewLine()
                if imgui.Button(u8'Вернуться в меню', imgui.ImVec2(-1, 25)) then  
                    Konst.v = false
                        WindowOne.v = true
                end
            imgui.End()
    end
end

function main()
    if not isSampLoaded() or not isSampfuncsLoaded() then return end
    while not isSampAvailable() do wait(100) end
        sampRegisterChatCommand('efk', function() WindowOne.v = not WindowOne.v imgui.Process = WindowOne.v end)

        if anotf then
            notify.addNotify('{02FFAB}[Konstant+EFK]{FFFFFF} Скрипт успешно загружен','Открыть меню, можно командой: {02FFAB}/efk\nАвтор скрипта: {02FFAB}TMoore',1,1,4)
        elseif not anotf then
            downloadUrlToFile('https://raw.githubusercontent.com/TMoore-frog/Downloads_Lib/main/lib_imgui_notf.lua','moonloader\\lib_imgui_notf.lua', function(id, status, p1, p2)
                if status == dlstatus.STATUS_ENDDOWNLOADDATA then
                    print('Файл lib_imgui_notf.lua был скачан')
                        print('Перезапускаю скрипт для установки!')
                            thisScript():reload()
                end
            end)
        end

        lua_thread.create(infinity)
end

function goupdate()
    sampAddChatMessage(('{02FFAB}[Konstant+EFK]{FFFFFF} Обнаружено обновление. AutoReload может конфликтовать. Обновляюсь...'), color)
    sampAddChatMessage(('{02FFAB}[Konstant+EFK]{FFFFFF} Текущая версия: '..thisScript().version..". Новая версия: "..version), color)
    wait(300)
    downloadUrlToFile(updatelink, thisScript().path, function(id3, status1, p13, p23) -- качает ваш файлик с latest version
        if status1 == dlstatus.STATUS_ENDDOWNLOADDATA then
            sampAddChatMessage(('{02FFAB}[Konstant+EFK]{FFFFFF} Обновление завершено!'), color)
                thisScript():reload()
        end
    end)
end

function update()
    local fpath = os.getenv('TEMP') .. '\\testing_version.json' -- куда будет качаться наш файлик для сравнения версии
    downloadUrlToFile('https://gist.githubusercontent.com/atiZZZ/7507f7d4a51dc036bd275b96cc7bed38/raw/a78a8ef401c553c4309efd6a80075f56567c6c93/atiz', fpath, function(id, status, p1, p2) -- ссылку на ваш гитхаб где есть строчки которые я ввёл в теме или любой другой сайт
        if status == dlstatus.STATUS_ENDDOWNLOADDATA then
        local f = io.open(fpath, 'r') -- открывает файл
        if f then
            local info = decodeJson(f:read('*a')) -- читает
                updatelink = info.updateurl
                if info and info.latest then
                version = tonumber(info.latest) -- переводит версию в число
                    if version > tonumber(thisScript().version) then -- если версия больше чем версия установленная то...
                        lua_thread.create(goupdate) -- апдейт
                    else -- если меньше, то
                        update = false -- не даём обновиться 
                            print('Ваша версия: '..thisScript().version)
                                print('Обновление не требуется')
                    end
                end
            end
        end
    end)
end